In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np
print(np.__version__)

2.5.2


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array created successfully:", arr)


Array created successfully: [1 2 3 4 5]


In [13]:
arr = np.linspace(1,10,20)
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
arr = np.zeros((2,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
import numpy as np
arr = np.random.randn(2,3)
arr

array([[-0.10576458, -2.23886109,  1.55665944],
       [ 0.65474358, -1.92773964, -0.65619692]])

In [20]:
arr1 = np.ones((2,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
arr = np.random.arr = np.random.randint(1,30,6)
arr


array([ 9,  5, 18,  3,  6,  5], dtype=int32)

ARRAY INDEXING AND ARRAY SLICING 

In [5]:
import numpy as np
arr = np.arange(11,21,3)
arr

array([11, 14, 17, 20])

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

ARTHEMTIC OPERTION IN ARRAY 



In [25]:

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

array2 + array2

array([12, 14, 16, 18, 20])

MATRIX MULTIPICATION

In [34]:
a = np.arange(1,31).reshape(5,6)

b = np.arange(30,60).reshape(5,6)
b
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [41]:
import numpy as np

b = np.array([[30, 31, 32, 33, 34, 35],
              [36, 37, 38, 39, 40, 41],
              [42, 43, 44, 45, 46, 47],
              [48, 49, 50, 51, 52, 53],
              [54, 55, 56, 57, 58, 59]])

a = np.array([[ 1,  2,  3,  4,  5,  6],
              [ 7,  8,  9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24],
              [25, 26, 27, 28, 29, 30]])

# Option 1: b ka transpose use kar
a @ b .T


array([[ 700,  826,  952, 1078, 1204],
       [1870, 2212, 2554, 2896, 3238],
       [3040, 3598, 4156, 4714, 5272],
       [4210, 4984, 5758, 6532, 7306],
       [5380, 6370, 7360, 8350, 9340]])

STACKING IN ARRAY

##VIRTICAL STACK IN ARRAY

In [44]:
a = np.vstack((array1,array2))

HORINZONTAL STACK IN ARRAY

In [49]:
a = np.hstack((array1,array2))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

COLUNM STACK

In [48]:
a = np.column_stack((array1,array2))
a

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

SPILTING ARRAY

In [55]:
a = np.arange(0,20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

VERTICAL SPILT

In [62]:
np.vsplit(a,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

HORIZONTAL SPILT

In [65]:
np.hsplit(a,5)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

                 EXCERSIES

In [74]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


# IS THIS SUDKO IS VALID OR NOT

np.sum(s,axis = 1)
np.sum(s,axis = 0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])